### ISSUE TITLE
Ничего не понятно

### ISSUE THREAD

**Issue by Galiks** [lexprom/modelling#1]
Где у тебя что, петух?

**Comment by lexprom** [comment]
АХахахах

**Comment by lexprom** [comment]
@Galiks дядя паша больше не приходить к нам в репозиторий :fearful:

**Comment by lexprom** [comment]
В силу недоразвитости спрашивающего закрываю ишью :white_check_mark:

**Comment by Galiks** [comment]
Себя закрой
